from django.views.generic import TemplateView
from django.urls import path
from attapp import views
urlpatterns=[
   # path('',TemplateView.as_view(template_name='index.html'),name='index'),
    path('',TemplateView.as_view(template_name='login.html'),name='login'),
    path('login',views.authenticate,name='subt'),
    path('signup/',TemplateView.as_view(template_name='signup.html'),name='signup'),
    path('signup',views.display,name='submit'),
    path('adminhome/',TemplateView.as_view(template_name='adminhome.html'),name='adminhome'),
    path('faculty_signup/',TemplateView.as_view(template_name='faculty_signup.html'),name='faculty_signup'),
    path('faculty_signup',views.signupfac,name='sub'),
    path('student_signup/',TemplateView.as_view(template_name='student_signup.html'),name='student_signup'),
    path('student_signup',views.signupstudent,name='submit'),
    path('student_home/',TemplateView.as_view(template_name='student_home.html'),name='student_home'),
    path('faculty_home/',TemplateView.as_view(template_name='faculty_home.html'),name='faculty_home'),
    path('fac_details/',TemplateView.as_view(template_name='fac_details.html'),name='fac_details'),
    path('fac_attendance/',TemplateView.as_view(template_name='fac_attendance.html'),name='fac_attendance'),
    path('stud_details/',TemplateView.as_view(template_name='stud_details.html'),name='stud_details'),
    path('stud_attendance/',TemplateView.as_view(template_name='stud_attendance.html'),name='stud_attendance'),
    path('attbyadmin',views.attbyadmin,name='stud_attendance'),
    path('stud_mark/',TemplateView.as_view(template_name='stud_mark.html'),name='stud_mark'),
    path('leave_mgmt/',TemplateView.as_view(template_name='leave_mgmt.html'),name='leave_mgmt'),
    path('timetable/',TemplateView.as_view(template_name='timetable.html'),name='timetable'),
    path('timetable',views.timeadmin,name='timetable'),
    path('fac_profile/',TemplateView.as_view(template_name='fac_profile.html'),name='fac_profile'),
    path('fac_profile',views.viewfac,name='fac_profile'),
    path('edit_fac',views.edit_fac,name='editf'),
    path('save_fac',views.save_fac,name='savef'),
    path('save_facd/',TemplateView.as_view(template_name='save_facd.html'),name='save_facd'),
    path('edit_stud',views.edit_stud,name='edits'),
    path('savestud',views.savestud,name='saves'),
    path('save_studd/',TemplateView.as_view(template_name='save_studd.html'),name='save_studd'),
    path('fac_applyleave/',TemplateView.as_view(template_name='fac_applyleave.html'),name='fac_applyleave'),
    path('fac_applyleave',views.leaveapply,name='sub'),
    path('fac_viewleave',views.facultyviewleave,name='fac_applyleave'),
    path('view_stud_details/',TemplateView.as_view(template_name='view_stud_details.html'),name='view_stud_details'),
    path('view_stud_attedance/',TemplateView.as_view(template_name='view_stud_attendance.html'),name='view_stud_attendance'),
    path('viewstudatten',views.addattendance,name='addatt'),
    #path('addstudatten',views.addattn,name='addatte'),
    path('vstudatten',views.statbyfac,name='view_stud_attendance'),
    path('view_stud_marks/',TemplateView.as_view(template_name='view_stud_marks.html'),name='view_stud_marks'),
    path('view_stud_marks',views.addmarks,name='submark'),
    path('view_timetable/',TemplateView.as_view(template_name='view_timetable.html'),name='view_timetable'),
    path('timetablestudnt/',TemplateView.as_view(template_name='timetablestudent.html'),name='timetablestudent'),
    path('stutime',views.timestudent,name='timetablestudent'),
    path('view_student_marks/',TemplateView.as_view(template_name='view_student_marks.html'),name='view_student_marks'),
    path('view_mymark',views.mymark,name='view_student_marks'),
    path('view_student_attedance/',TemplateView.as_view(template_name='view_student_attendance.html'),name='view_student_attendance'),
    path('myatten',views.myattendance,name='view_student_attendance'),
    path('viewleavestud',TemplateView.as_view(template_name='viewleavestud.html'),name='viewleavestud'),
    path('viewleavest',views.approvestud,name='aprv'),
    path('viewleavef',views.approvefac,name='aprvf'),
    path('viewleastu',views.viewleavest,name='viewleavestud'),
    path('student_applyleave/',TemplateView.as_view(template_name='student_applyleave.html'),name='student_applyleave'),
    path('stuapplyleave',views.stuapplyleave,name='stuapply'),
    path('stuviewleave',views.stuviewleave,name='student_applyleave'),
    path('view_student_details/',TemplateView.as_view(template_name='view_student_details.html'),name='view_student_details'),
    path('jsd2attendance/',TemplateView.as_view(template_name='jsd2attendance.html'),name='jsd2attendance'),
    path('jsd2attendance',views.viewatt,name='jsd2attendance'),
    path('viewstud',views.viewstud,name='stud_details'),
    path('facdet',views.facdet,name='fac_details'),
    path('view_stud',views.view_stud,name='view_stud_details'),
    path('stuprof',views.stuprof,name='view_student_details'),
    
    path('viewleavefac/',TemplateView.as_view(template_name='viewleavefac.html'),name='viewleavefac'),
    path('viewleavefac',views.viewleavef,name='viewleavefac'),
    
    path('viewmarkbyfac',views.viewmarkbyfac,name='view_stud_marks'),
    path('viewmarkbyadmin',views.viewmarkbyadmin,name='stud_mark'),
    
    path('timetable_fac/',TemplateView.as_view(template_name='timetable_fac.html'),name='timetable_fac'),
    path('timefac',views.timefac,name='timetable_fac'),
    path('logout/',views.logout_view,name='logout'),
   ]
