# Generated by Django 3.0 on 2020-01-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='fac_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facid', models.IntegerField()),
                ('date', models.DateField()),
                ('status_h1', models.CharField(max_length=5)),
                ('status_h2', models.CharField(max_length=5)),
                ('status_h3', models.CharField(max_length=5)),
                ('status_h4', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('facid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('batchincharge', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsid', models.IntegerField()),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('reason', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid_id', models.IntegerField()),
                ('assno', models.IntegerField()),
                ('sub1', models.IntegerField()),
                ('sub2', models.IntegerField()),
                ('sub3', models.IntegerField()),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('mob', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stud_att',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.IntegerField()),
                ('date', models.DateField()),
                ('status_h1', models.CharField(max_length=5)),
                ('status_h2', models.CharField(max_length=5)),
                ('status_h3', models.CharField(max_length=5)),
                ('status_h4', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('stid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('admissionno', models.IntegerField(blank=True, null=True)),
                ('admissiondate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('guardian', models.CharField(blank=True, max_length=20, null=True)),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
