# Generated by Django 3.0 on 2020-01-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('reason', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
