# Generated by Django 3.0 on 2020-01-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0002_sleave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stud_att',
        ),
    ]
