# Generated by Django 3.0 on 2020-01-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0003_delete_stud_att'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud_att',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.IntegerField()),
                ('date', models.DateField()),
                ('status_h1', models.CharField(max_length=5)),
                ('status_h2', models.CharField(max_length=5)),
                ('status_h3', models.CharField(max_length=5)),
                ('status_h4', models.CharField(max_length=5)),
            ],
        ),
    ]
