# Generated by Django 3.0 on 2020-01-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0004_stud_att'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=10)),
                ('hour1', models.CharField(max_length=10)),
                ('hour2', models.CharField(max_length=10)),
                ('hour3', models.CharField(max_length=10)),
                ('hour4', models.CharField(max_length=10)),
            ],
        ),
    ]
