# Generated by Django 3.0 on 2020-01-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0005_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leave',
        ),
    ]
