# Generated by Django 3.0 on 2020-01-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0007_fleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_att',
            name='status_h1',
            field=models.CharField(default='present', max_length=5),
        ),
    ]
