# Generated by Django 3.0 on 2020-01-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0008_auto_20200109_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_att',
            name='status_h2',
            field=models.CharField(default='present', max_length=5),
        ),
        migrations.AlterField(
            model_name='stud_att',
            name='status_h3',
            field=models.CharField(default='present', max_length=5),
        ),
        migrations.AlterField(
            model_name='stud_att',
            name='status_h4',
            field=models.CharField(default='present', max_length=5),
        ),
    ]
