# Generated by Django 3.0 on 2020-01-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0009_auto_20200109_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='satt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.BinaryField()),
            ],
        ),
    ]
